# Generated by Django 4.0.3 on 2022-03-18 23:40

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, db_column='_id', primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('ups', djongo.models.fields.JSONField(blank=True, default=list, null=True)),
                ('ups_count', models.PositiveIntegerField()),
                ('downs', djongo.models.fields.JSONField(blank=True, default=list, null=True)),
                ('downs_count', models.PositiveIntegerField()),
                ('comments', djongo.models.fields.JSONField(blank=True, default=list, null=True)),
                ('comments_count', models.PositiveIntegerField()),
                ('date', models.DateField()),
            ],
            options={
                'db_table': 'Comment',
            },
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, db_column='_id', primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('ups', djongo.models.fields.JSONField(blank=True, default=list, null=True)),
                ('ups_count', models.PositiveIntegerField()),
                ('downs', djongo.models.fields.JSONField(blank=True, default=list, null=True)),
                ('downs_count', models.PositiveIntegerField()),
                ('comments', djongo.models.fields.JSONField(blank=True, default=list, null=True)),
                ('comments_count', models.PositiveIntegerField()),
                ('date', models.DateField()),
                ('author', models.TextField()),
                ('enabled', models.BooleanField()),
                ('days_to_die', models.PositiveIntegerField(default=7)),
            ],
            options={
                'db_table': 'Quote',
            },
        ),
    ]
