# Generated by Django 4.0.3 on 2022-03-19 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0003_alter_comment_date_alter_quote_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='original_quote',
            field=models.TextField(default=''),
        ),
    ]
